model:
  task: gemnet
  name: gemnet
  dataset: ZC
  exp_path: /cpfs01/projects-HDD/cfff-282dafecea22_HDD/zhouzhijian/Work/Experiment
  log_path: /cpfs01/projects-HDD/cfff-282dafecea22_HDD/zhouzhijian/Work/Log
  batch_size: 256
  epoch_num: 100
  learning_rate: 0.0005
  seed: 3407
  print_steps: 50
  val_freq: 5
  
  num_targets: 1
  regress_forces: False
  otf_graph: True
  num_spherical: 7
  num_radial: 128
  num_blocks: 4
  emb_size_atom: 256
  emb_size_edge: 512
  emb_size_trip_in: 64
  emb_size_trip_out: 64
  emb_size_quad_in: 32
  emb_size_quad_out: 32
  emb_size_aint_in: 64
  emb_size_aint_out: 64
  emb_size_rbf: 16
  emb_size_cbf: 16
  emb_size_sbf: 32
  num_before_skip: 2
  num_after_skip: 2
  num_concat: 1
  num_atom: 3
  num_output_afteratom: 3
  cutoff: 12.0
  cutoff_qint: 12.0
  cutoff_aeaint: 12.0
  cutoff_aint: 12.0
  max_neighbors: 30
  max_neighbors_qint: 8
  max_neighbors_aeaint: 20
  max_neighbors_aint: 1000

loss:
  loss_fuction: {"energy": "mae"}
  real_loss_need: True
  loss_weight: {"energy": 1.0}
  norm_need: True
  
dataset:
  name: ZCDataset
  config_path: False
  target: ["energy"]
  root: /cpfs01/projects-HDD/cfff-282dafecea22_HDD/zhouzhijian/Work/Data/ZC_new
  force: False
  processdir: processed

schedular:
  warmup_steps: 1000
  max_lr: 0.0005
  base_lr: 0.0000001
  strategy: "Linear"
  strategy_param:
    mode: "min"
    factor: 0.8
    patience: 2
    start_factor: 1
    end_factor: 0.0001
    total_iters: 100





