model:
  task: escn
  name: eScN
  dataset: ZC
  exp_path: /cpfs01/projects-HDD/cfff-282dafecea22_HDD/zhouzhijian/Work/Experiment
  log_path: /cpfs01/projects-HDD/cfff-282dafecea22_HDD/zhouzhijian/Work/Log
  cuda_idx: 2
  batch_size: 128
  epoch_num: 50
  learning_rate: 0.0001
  seed: 3407
  print_steps: 50
  val_freq: 5

  num_layers: 4
  max_neighbors: 30
  cutoff: 6.0
  max_num_elements: 90
  sphere_channels: 128
  hidden_channels: 256
  lmax_list: [6]
  mmax_list: [2]
  num_sphere_samples: 128
  distance_function: "gaussian"
  regress_forces: False
  basis_width_scalar: 2.0
  otf_graph: True

loss:
  loss_fuction: {"energy": "mae"}
  real_loss_need: True
  loss_weight: {"energy": 1.0}
  norm_need: True
dataset:
  name: ZCDataset
  config_path: False
  target: ["energy"]
  root: /cpfs01/projects-HDD/cfff-282dafecea22_HDD/zhouzhijian/Work/Data/ZC
  force: False
  processdir: processed
schedular:
  warmup_steps: 1000
  max_lr: 0.0001
  base_lr: 0.0000001
  strategy: "Linear"
  strategy_param:
    mode: "min"
    factor: 0.8
    patience: 0.5
    start_factor: 1
    end_factor: 0.01
    total_iters: 50





