model:
  task: SchNet
  name: SchNet
  dataset: qm9
  exp_path: /cpfs01/projects-HDD/cfff-282dafecea22_HDD/zhouzhijian/Work/Experiment
  log_path: /cpfs01/projects-HDD/cfff-282dafecea22_HDD/zhouzhijian/Work/Log
  cuda_idx: 0
  batch_size: 64
  epoch_num: 100
  learning_rate: 0.001
  seed: 3407
  print_steps: 50
  val_freq: 5

  hidden_channels:  128
  num_filters: 128
  num_interactions: 6
  num_gaussians: 50
  cutoff: 10.0
  max_num_neighbors: 32
  atomref: True
loss:
  loss_fuction: {"energy": "mae"}
  real_loss_need: True
  loss_weight: {"energy": 1.0}
  norm_need: False
dataset:
  name: QMDataset
  config_path: False
  target: ["energy"]
  root: /cpfs01/projects-HDD/cfff-282dafecea22_HDD/zhouzhijian/Work/Data/qm9
  force: False
  processdir: processed
schedular:
  warmup_steps: 1000
  max_lr: 0.0001
  base_lr: 0.0000001
  strategy: "Linear"
  stratege_param:
    mode: "min"
    fator: 0.8
    patience: 0.5
    start_factor: 1
    end_factor: 0.01
    total_iters: 50





