model:
  task: escn
  name: eScN
  dataset: qm9
  exp_path: /cpfs01/projects-HDD/cfff-282dafecea22_HDD/zhouzhijian/Work/Experiment
  log_path: /cpfs01/projects-HDD/cfff-282dafecea22_HDD/zhouzhijian/Work/Log
  cuda_idx: 1
  batch_size: 64
  epoch_num: 100
  learning_rate: 0.001
  seed: 3407
  print_steps: 50
  val_freq: 5

  num_layers: 12
  max_neighbors: 20
  cutoff: 12.0
  sphere_channels: 128
  hidden_channels: 256
  lmax_list: [6]
  mmax_list: [2]
  num_sphere_samples: 128
  distance_function: "gaussian"
  regress_forces: True
  basis_width_scalar: 2.0
  otf_graph: True

loss:
  loss_fuction: {"energy": "mae"}
  real_loss_need: True
  loss_weight: {"energy": 1.0}
  norm_need: False
dataset:
  name: QMDataset
  config_path: False
  target: ["energy"]
  root: /cpfs01/projects-HDD/cfff-282dafecea22_HDD/zhouzhijian/Work/Data/qm9
  force: False
  processdir: processed
optimizer:
  ex_decay: 0.9
  ex_decay_freq: 1





